export { default as DefaultDatatable } from "./DefaultDatatable.svelte";
export { default as TableSearch } from "./TableSearch.svelte";
export { default as FilteringData } from "./FilteringData.svelte";
export { default as SortingData } from "./SortingData.svelte";
export { default as TablePagination } from "./TablePagination.svelte";
export { default as SelectingRows } from "./SelectingRows.svelte"
export { default as Custom } from "./Custom.svelte"
export { default as Simple } from "./Simple.svelte"
export { default as CustomCell } from "./CustomCell.svelte"